// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
//By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

package main

var sum int = 0
var first_num int = 1
var second_num int = 2
var third_num int = 1

func main() {

	for third_num < 4000000 {

		if first_num%2 == 0 {
			sum += first_num
		}

		if second_num%2 == 0 {
			sum += second_num
		}

		third_num = first_num + second_num
		second_num = third_num + second_num
		first_num = third_num

	}

	print(sum)
}
